apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 320-cloud-pak-for-data-db2oltp
  labels:
    type: software
    code: '320'
  annotations:
    displayName: DB2 OLTP for Cloud Pak for Data
    description: GitOps deployment of DB2 OLTP for Cloud pak for Data
    apply-all/optional: 'true'
    deployment-type/gitops: 'true'
spec:
  modules:
    - name: gitops-db2-oltp
      alias: gitops-db2-oltp
      version: v1.0.12
      variables:
        - name: common_services_namespace
          alias: ibm_common_services_namespace
          scope: global
        - name: operator_namespace
          alias: cpd_operators_namespace
          scope: global
        - name: cpd_namespace
          alias: cp4d_namespace
          scope: global
        - name: subscription_source_namespace
          value: openshift-marketplace
        - name: license
          value: Advanced
        - name: channel
          value: v1.0
        - name: namespace
          value: gitops-cp-db2oltp
      dependencies:
        - name: namespace
          ref: gitops-cp-db2oltp_namespace
        - name: namespace
          optional: true
        - name: gitops-db2u
          optional: true
        - name: gitops-cp4d-instance
          optional: true
        - name: cp4d-instance
          optional: true
        - name: gitops-cp4d-operator
          optional: true
        - name: gitops-cp-catalogs
          optional: true
        - name: ibm-common-service
          optional: true
    - name: gitops-namespace
      alias: gitops-cp-db2oltp_namespace
      version: v1.0.11
      variables:
        - name: name
          value: gitops-cp-db2oltp
    - name: gitops-repo
      alias: gitops_repo
      version: v1.21.0
    - name: util-clis
      version: v1.16.9
  variables:
    - name: cpd_operators_namespace
      type: string
      description: CPD operator namespace
      defaultValue: cpd-operators
    - name: cp4d_namespace
      type: string
      description: CPD namespace
      defaultValue: cp4d
    - name: ibm_common_services_namespace
      type: string
      description: IBM Common Services namespace
      defaultValue: ibm-common-services
    - name: gitops_repo_host
      type: string
      description: >-
        The host for the git repository. The git host used can be a GitHub,
        GitHub Enterprise, Gitlab, Bitbucket, Gitea or Azure DevOps server. If
        the host is null assumes in-cluster Gitea instance will be used.
      defaultValue: ''
    - name: gitops_repo_org
      type: string
      description: >-
        The org/group where the git repository exists/will be provisioned. If
        the value is left blank then the username org will be used.
      defaultValue: ''
    - name: gitops_repo_project
      type: string
      description: >-
        The project that will be used for the git repo. (Primarily used for
        Azure DevOps repos)
      defaultValue: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      defaultValue: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      defaultValue: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
