apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 305-cloud-pak-for-data-foundation
  labels:
    type: software
    code: '305'
  annotations:
    displayName: Data Foundation
    description: GitOps deployment of Data Foundation for Cloud pak for Data
    deployment-type/gitops: 'true'
spec:
  modules:
    - name: cp4d-instance
      alias: cp4d-instance
      version: v1.0.7
      dependencies:
        - name: namespace
          ref: cp4d_namespace
      variables:
        - name: storage_vendor
          value: portworx
    - name: gitops-cp-catalogs
      alias: gitops-cp-catalogs
      version: v1.2.6
      dependencies:
        - name: namespace
          ref: ibm_common_services_namespace
      variables:
        - name: entitlement_key
          scope: global
    - name: gitops-cp4d-operator
      alias: gitops-cp4d-operator
      version: v1.0.1
      dependencies:
        - name: namespace
          ref: cpd_operators_namespace
        - name: ibm-common-service
          optional: true
    - name: gitops-namespace
      alias: ibm_common_services_namespace
      version: v1.14.0
      variables:
        - name: name
          alias: ibm_common_services_namespace
          scope: global
    - name: gitops-namespace
      alias: cpd_operators_namespace
      version: v1.14.0
      variables:
        - name: name
          alias: cpd_operators_namespace
          scope: global
    - name: gitops-namespace
      alias: cp4d_namespace
      version: v1.14.0
      variables:
        - name: name
          alias: cp4d_namespace
          scope: global
    - name: gitops-repo
      alias: gitops_repo
      version: v1.23.1
    - name: util-clis
      version: v1.18.1
  variables:
    - name: gitops_default_host
      type: string
    - name: gitops_default_org
      type: string
    - name: gitops_default_username
      type: string
    - name: gitops_default_token
      type: string
      sensitive: true
    - name: gitops_default_ca_cert
      type: string
    - name: entitlement_key
      type: string
      description: >-
        The entitlement key used to access the CP4I images in the container
        registry. Visit https://myibm.ibm.com/products-services/containerlibrary
        to get the key
      sensitive: true
    - name: ibm_common_services_namespace
      type: string
      description: The value that should be used for the namespace
      defaultValue: ibm-common-services
    - name: cpd_operators_namespace
      type: string
      description: The value that should be used for the namespace
      defaultValue: cpd-operators
    - name: cp4d_namespace
      type: string
      description: The value that should be used for the namespace
      defaultValue: cp4d
    - name: gitops_repo_host
      type: string
      description: >-
        The host for the git repository. The git host used can be a GitHub,
        GitHub Enterprise, Gitlab, Bitbucket, Gitea or Azure DevOps server. If
        the host is null assumes in-cluster Gitea instance will be used.
      defaultValue: ''
    - name: gitops_repo_org
      type: string
      description: >-
        The org/group where the git repository exists/will be provisioned. If
        the value is left blank then the username org will be used.
      defaultValue: ''
    - name: gitops_repo_project
      type: string
      description: >-
        The project that will be used for the git repo. (Primarily used for
        Azure DevOps repos)
      defaultValue: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      defaultValue: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      defaultValue: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
