apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 310-cloud-pak-for-data-db2uoperator
  labels:
    type: software
    code: '310'
  annotations:
    displayName: DB2UOperator for Cloud Pak for Data
    description: GitOps deployment of DB2U Operator for Cloud pak for Data
    apply-all/optional: 'true'
    deployment-type/gitops: 'true'
spec:
  modules:
    - name: gitops-db2u
      alias: gitops-db2u
      version: v1.1.0
      variables:
        - name: operator_namespace
          alias: cpd_operators_namespace
          scope: global
        - name: channel
          value: v1.1
        - name: subscription_source_namespace
          value: openshift-marketplace
      dependencies:
        - name: namespace
          ref: gitops-db2u_namespace
        - name: namespace
          optional: true
        - name: gitops-cp4d-instance
          optional: true
        - name: cp4d-instance
          optional: true
        - name: gitops-cp4d-operator
          optional: true
        - name: gitops-cp-catalogs
          optional: true
        - name: ibm-common-service
          optional: true
    - name: gitops-namespace
      alias: gitops-db2u_namespace
      version: v1.11.2
      variables:
        - name: name
          value: gitops-db2u
    - name: gitops-repo
      alias: gitops_repo
      version: v1.18.1
  variables:
    - name: cpd_operators_namespace
      type: string
      description: The namespace where the operators will be installed
      defaultValue: cpd-operators
    - name: gitops_repo_host
      type: string
      description: The host for the git repository.
      defaultValue: ''
    - name: gitops_repo_org
      type: string
      description: The org/group where the git repository exists/will be provisioned.
      defaultValue: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      defaultValue: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      defaultValue: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
