apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 300-cloud-pak-for-data-entitlement
  labels:
    type: software
    code: '300'
  annotations:
    displayName: IBM Cloud Pak for Data - Entitlement
    description: GitOps deployment of Entitlement for Cloud pak for Data
    deployment-type/gitops: 'true'
spec:
  modules:
    - name: gitops-global-pullsecret-synch
      alias: gitops-global-pullsecret-synch
      version: v0.1.2
      dependencies:
        - name: namespace
          ref: entitlements_namespace
    - name: gitops-module-global-pullsecret
      alias: gitops-module-global-pullsecret
      version: v0.0.1
      dependencies:
        - name: namespace
          ref: entitlements_namespace
      variables:
        - name: docker_server
          value: cp.icr.io
          scope: global
        - name: docker_username
          value: cp
          scope: global
        - name: secret_name
          value: cp4d-entitlement-key
          scope: global
        - name: docker_password
          alias: entitlement_key
          scope: global
    - name: gitops-namespace
      alias: entitlements_namespace
      version: v1.12.3
      variables:
        - name: name
          value: entitlements
    - name: gitops-repo
      alias: gitops_repo
      version: v1.21.0
  variables:
    - name: entitlement_key
      type: string
      description: The password for the container registry
      sensitive: true
    - name: gitops_repo_host
      type: string
      description: >-
        The host for the git repository. The git host used can be a GitHub,
        GitHub Enterprise, Gitlab, Bitbucket, Gitea or Azure DevOps server. If
        the host is null assumes in-cluster Gitea instance will be used.
      defaultValue: ''
    - name: gitops_repo_org
      type: string
      description: >-
        The org/group where the git repository exists/will be provisioned. If
        the value is left blank then the username org will be used.
      defaultValue: ''
    - name: gitops_repo_project
      type: string
      description: >-
        The project that will be used for the git repo. (Primarily used for
        Azure DevOps repos)
      defaultValue: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      defaultValue: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      defaultValue: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
